var Citys = {
  'totalResultsCount':10,
  'geonames':[
    {
      'countryName':'United States',
      'adminCode1':'MO',
      'fclName':'city, village,...',
      'countryCode':'US',
      'lng':-94.891913,
      'fcodeName':'populated place',
      'toponymName':'Amazonia',
      'fcl':'P',
      'name':'Amazonia',
      'fcode':'PPL',
      'geonameId':4374751,
      'lat':39.8861052,
      'adminName1':'Missouri',
      'population':312
    },
    {
      'countryName':'Brazil',
      'adminCode1':'00',
      'fclName':'mountain,hill,rock,... ',
      'countryCode':'BR',
      'lng':-60,
      'fcodeName':'depression(s)',
      'toponymName':'Amazonia',
      'fcl':'T',
      'name':'Amazonia',
      'fcode':'DPR',
      'geonameId':3407731,
      'lat':-2.5,
      'adminName1':'',
      'population':0
    },
    {
      'countryName':'Brazil',
      'adminCode1':'05',
      'fclName':'city, village,...',
      'countryCode':'BR',
      'lng':-39.3333333,
      'fcodeName':'populated place',
      'toponymName':'Amazonia',
      'fcl':'P',
      'name':'Amazonia',
      'fcode':'PPL',
      'geonameId':3472360,
      'lat':-12.1666667,
      'adminName1':'Bahia',
      'population':0},
    {
      'countryName':'Colombia',
      'adminCode1':'00',
      'fclName':'parks,area, ...',
      'countryCode':'CO',
      'lng':-72.5,
      'fcodeName':'region',
      'toponymName':'Amazonia',
      'fcl':'L',
      'name':'Amazonia',
      'fcode':'RGN',
      'geonameId':3689981,
      'lat':0.5,
      'adminName1':'',
      'population':0
    },
    {
      'countryName':'United States',
      'adminCode1':'NV',
      'fclName':'spot, building, farm',
      'countryCode':'US',
      'lng':-117.0792575,
      'fcodeName':'mine(s)',
      'toponymName':'Amazonia Mine',
      'fcl':'S',
      'name':'Amazonia Mine',
      'fcode':'MN',
      'geonameId':5499217,
      'lat':39.5588137,
      'adminName1':'Nevada',
      'population':0
    },
    {
      'countryName':'United States',
      'adminCode1':'MO',
      'fclName':'spot, building, farm',
      'countryCode':'US',
      'lng':-94.8936525,
      'fcodeName':'school',
      'toponymName':'Amazonia Elementary School',
      'fcl':'S',
      'name':'Amazonia Elementary School',
      'fcode':'SCH',
      'geonameId':4374752,
      'lat':39.8924274,
      'adminName1':'Missouri',
      'population':0
    },
    {
      'countryName':'Portugal',
      'adminCode1':'19',
      'fclName':'spot, building, farm',
      'countryCode':'PT',
      'lng':-8.8993,
      'fcodeName':'hotel',
      'toponymName':'Amazonia Palmela Apartamentos Turísticos',
      'fcl':'S',
      'name':'Amazonia Palmela Apartamentos Turísticos',
      'fcode':'HTL',
      'geonameId':6498568,
      'lat':38.5667,
      'adminName1':'Setúbal',
      'population':0
    },
    {
      'countryName':'Portugal',
      'adminCode1':'14',
      'fclName':'spot, building, farm',
      'countryCode':'PT',
      'lng':-9.3969,
      'fcodeName':'hotel',
      'toponymName':'Amazonia Lennox Estoril',
      'fcl':'S',
      'name':'Amazonia Lennox Estoril',
      'fcode':'HTL',
      'geonameId':6498602,
      'lat':38.7041,
      'adminName1':'Lisbon',
      'population':0
    },
    {
      'countryName':'Portugal',
      'adminCode1':'14',
      'fclName':'spot, building, farm',
      'countryCode':'PT',
      'lng':-9.2656,
      'fcodeName':'hotel',
      'toponymName':'Amazonia Jamor Hotel',
      'fcl':'S',
      'name':'Amazonia Jamor Hotel',
      'fcode':'HTL',
      'geonameId':6499271,
      'lat':38.7152,
      'adminName1':'Lisbon',
      'population':0
    },
    {
      'countryName':'Portugal',
      'adminCode1':'14',
      'fclName':'spot, building, farm',
      'countryCode':'PT',
      'lng':-9.155,
      'fcodeName':'hotel',
      'toponymName':'Amazonia Lisboa Hotel',
      'fcl':'S',
      'name':'Amazonia Lisboa Hotel',
      'fcode':'HTL',
      'geonameId':6499665,
      'lat':38.723,
      'adminName1':'Lisbon',
      'population':0
    }
  ]
}
